 classDiagram
      DataEntities --|> PublicEntities : PublicEntities.Name = DataEntities.PublicEntityName
      PublicEntities --|> PublicEnumerations : PublicEntities.TypeName = PublicEnumerations.Name
      Labels <-- DataEntities : LabelId
      Labels <|-- PublicEntities : LabelId
      Labels <|-- PublicEnumerations : LabelId
      class Labels{
          +String Id
          +String Language
      }
      class DataEntities{
          +String Name
          +String PublicEntityName
          +String PublicCollectionName
          +String LabelId
      }
      class PublicEntities{
          +String Name
          +String EntitySetName
          +String LabelId
      }
      class PublicEnumerations{
          +String Name
          +String LabelId
      }